<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Indexing_Worker-93651a63-6415-40a1-93a4-06df12567700</UserSecretsId>
    <RootNamespace>Indexing_Worker</RootNamespace>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Apm" Version="1.34.1" />
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="8.15.0" />
    <PackageReference Include="Elasticsearch.Net" Version="7.17.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
  </ItemGroup>
</Project>
